### ISSUE TITLE
[Question] Performance considerations and usage?

### ISSUE THREAD

**Issue by chartpath** [Narnach/torm#6]
Hi @Narnach thanks for creating this interesting project! I really like the way you are handling the priority of the rules and the cascading overrule behaviour.

I've been playing with different forward chaining logic things for a while and have just accepted the gospel that the Rete algorithm is the best way to scale rule valuation. E.g. as implemented by CLIPS. But I'm not a computer scientist.

Have you had a chance to load test torm yet? I'm curious how well ruby can handle various numbers of facts and rules.

Lastly, let's say we wanted to find all rules that can decide a given fact, to use for generating prompts to fetch more user input. Would that be to call `rules_for()`, and then just calling `decide` when there is nothing left to gather?

**Comment by Narnach** [comment]
Hey Chris!

This was extracted from a client project about 7 years ago. To be honest it was just a practical solution to our problem. We needed very strict levels of overrides and the rules were never _too_ complex. Not being a computer scientist either, I don't know much about Rete or CLIPS 😅 

Torm has been used to determine rules in two separate places:

- A modular frontend system which had to decide if specific widgets should or should not display certain aspects of themselves. This was to comply with multiple layers of regulations and company preferences.
- A content distribution platform which had to determine if videos, mobile games and other mobile content were allowed to be offered to users based on multiple layers of regulations and company preferences.

These systems have served on modest VPS hardware (4-core Linode), servicing load spikes of over 100k requests/hour (IIRC) for the frontend system. Torm was never a bottleneck compared to making API calls, rendering views, database access, and other things we did. In-memory systems tend to be _fast_.

Your second question is interesting, because it's a different angle to how we used Torm.

`Torm.instance.rules` stores all defined rules. It has a `private` method `#conditions_whitelist_for` which is used by [`add_rule`](https://github.com/Narnach/torm/blob/d555662d6ec25c2116d8839fa153b6ed4b8d85ef/lib/torm/rules_engine.rb#L42) to store all relevant conditions for an individual rule. This might be a good place to start looking to see if it helps you move forward. Thanks to Ruby you can use `#send` to bypass private restrictions and see if it works for you.

If you manage to get a good use case going, I'd love to see a  PR with a bit of documentation for your use case and maybe some relevant changes to support it (such as adding a convenience method on `Torm.instance` to query the info you need) with some tests to support this.

Cheers,

Wes

**Comment by chartpath** [comment]
Awesome, thanks Wes! Can't wait to find time to try it out.
